# Generated by Django 6.0.4 on 2026-04-11 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Пункт чеклиста')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Пункт чеклиста',
                'verbose_name_plural': 'Пункты чеклиста',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('result_updated', 'Обновление пункта'), ('cabinet_toggled', 'Изменение участия кабинета'), ('all_reset', 'Сброс чеклиста'), ('item_created', 'Создание пункта'), ('item_deleted', 'Удаление пункта')], max_length=32, verbose_name='Действие')),
                ('cabinet_name', models.CharField(blank=True, max_length=32, verbose_name='Кабинет')),
                ('item_title', models.CharField(blank=True, max_length=255, verbose_name='Пункт')),
                ('status', models.CharField(blank=True, max_length=16, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Кабинет')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('can_be_skipped', models.BooleanField(default=False, verbose_name='Можно пропустить')),
                ('included', models.BooleanField(default=True, verbose_name='Участвует в проверке')),
                ('availability_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда меняли участие')),
                ('availability_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_availability_updates', to=settings.AUTH_USER_MODEL, verbose_name='Кто менял участие')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unchecked', 'Не проверено'), ('done', 'Выполнено'), ('problem', 'Проблема')], default='unchecked', max_length=16, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда обновили')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.cabinet', verbose_name='Кабинет')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.checklistitem', verbose_name='Пункт чеклиста')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_updates', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил')),
            ],
            options={
                'verbose_name': 'Результат проверки',
                'verbose_name_plural': 'Результаты проверки',
                'ordering': ('cabinet__sort_order', 'item__sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('cabinet', 'item'), name='unique_checklist_result')],
            },
        ),
    ]
