# Generated by Django 6.0.4 on 2026-04-11 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seed_cabinets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unchecked', 'Не проверено'), ('done', 'Выполнено'), ('problem', 'Проблема')], default='unchecked', max_length=16, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда обновили')),
                ('cabinet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_check', to='main.cabinet', verbose_name='Кабинет')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_check_updates', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил')),
            ],
            options={
                'verbose_name': 'Статус кабинета',
                'verbose_name_plural': 'Статусы кабинетов',
                'ordering': ('cabinet__sort_order', 'cabinet__name'),
            },
        ),
        migrations.CreateModel(
            name='InspectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1, verbose_name='Номер обхода')),
                ('last_reset_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда начат обход')),
                ('last_reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_resets', to=settings.AUTH_USER_MODEL, verbose_name='Кто запустил обход')),
            ],
            options={
                'verbose_name': 'Текущий обход',
                'verbose_name_plural': 'Текущий обход',
            },
        ),
    ]
